name: Test compilation

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:

      # - name: Try to restore opam cache
      #   id: opam-cache
      #   uses: actions/cache@v4
      #   with:
      #     path: "~/.opam"
      #     key: opamdir-${{github.base_ref}}-${{github.ref}}
      #     restore-keys: |
      #       opamdir--refs/heads/${{github.base_ref}}

      - name: Checkout code
        uses: actions/checkout@v5
        with:
          fetch-depth: 1

      - name: Install OCaml
        uses: ocaml/setup-ocaml@v3
        with:
          ocaml-compiler: 4.11.0
          opam-disable-sandboxing: true
          opam-repositories: "{ default: https://github.com/ocaml/opam-repository.git, coq-released: https://coq.inria.fr/opam/released, coq-extra-dev: https://coq.inria.fr/opam/extra-dev }"

      - run: opam install . --deps-only --with-doc --with-test

      - run: opam exec -- make -j 2 all
